/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta;

/**
 *
 * @author reza
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener; 
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;
import java.awt.Point;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import ta.flm;
public class bioskop extends javax.swing.JFrame {
    int i = 0;
    int s = 1;
    koneksiDB x;
    public Connection conn;
    public ResultSet rs;
    public Statement st;
    public PreparedStatement pst;
 
    /**
     
     */
    
    
    public bioskop() throws SQLException {
        this.jamberjalan = jamberjalan;
        initComponents();
        
        x = new koneksiDB();
        x.koneksi();
        conn = null;
        conn = DriverManager.getConnection("jdbc:mysql://localhost/inputan","root","");
        
        Timer t2 = new Timer();
        t2.scheduleAtFixedRate( new TimerTask (){
            @Override
            public void run(){
                waktuBerjalan.setText(new SimpleDateFormat("EEEE dd-MM-yyyy").format(new java.util.Date()));
                jamberjalan.setText(new SimpleDateFormat("hh:mm:ss").format(new java.util.Date()));           
            }
        },0,1000);
       
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        g1 = new javax.swing.JLabel();
        g2 = new javax.swing.JLabel();
        g3 = new javax.swing.JLabel();
        g4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnexit = new javax.swing.JButton();
        btnexit1 = new javax.swing.JButton();
        btnexit2 = new javax.swing.JButton();
        btnexit3 = new javax.swing.JButton();
        btnexit4 = new javax.swing.JButton();
        waktuBerjalan = new javax.swing.JLabel();
        jamberjalan = new javax.swing.JLabel();
        label1 = new javax.swing.JTextField();
        label2 = new javax.swing.JTextField();
        label3 = new javax.swing.JTextField();
        label4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        f1 = new javax.swing.JTextField();
        f2 = new javax.swing.JTextField();
        f3 = new javax.swing.JTextField();
        f4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));
        setUndecorated(true);
        setSize(new java.awt.Dimension(500, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jButton1.setForeground(new java.awt.Color(153, 255, 255));
        jButton1.setText("Pesan");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);

        jButton2.setForeground(new java.awt.Color(153, 255, 255));
        jButton2.setText("Pesan");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 3));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);

        jButton3.setForeground(new java.awt.Color(153, 255, 255));
        jButton3.setText("Pesan");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 3));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setOpaque(false);
        jButton3.setContentAreaFilled(false);

        jButton4.setForeground(new java.awt.Color(153, 255, 255));
        jButton4.setText("Pesan");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 3));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setOpaque(false);
        jButton4.setContentAreaFilled(false);

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("08.00");

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("12.00");

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("15.00");

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("20.00");

        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("12.00");

        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("15.00");

        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("20.00");

        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("08.00");

        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("12.00");

        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("15.00");

        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("20.00");

        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("08.00");

        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("12.00");

        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("15.00");

        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("20.00");

        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("08.00");

        jLabel21.setFont(new java.awt.Font("Roboto Slab", 3, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 255, 255));
        jLabel21.setText("Bioskop Sam Reza");

        g1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ta/g1.jpg"))); // NOI18N

        g2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ta/g2.jpg"))); // NOI18N

        g3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ta/g3.png"))); // NOI18N

        g4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ta/g4.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        btnexit.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnexit.setForeground(new java.awt.Color(0, 102, 102));
        btnexit.setText("EXIT");
        btnexit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        btnexit.setContentAreaFilled(false);
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btnexit1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btnexit1.setForeground(new java.awt.Color(0, 102, 102));
        btnexit1.setText("RESET");
        btnexit1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        btnexit1.setContentAreaFilled(false);
        btnexit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexit1ActionPerformed(evt);
            }
        });

        btnexit2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btnexit2.setForeground(new java.awt.Color(0, 102, 102));
        btnexit2.setText("Snack");
        btnexit2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        btnexit2.setContentAreaFilled(false);
        btnexit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexit2ActionPerformed(evt);
            }
        });

        btnexit3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btnexit3.setForeground(new java.awt.Color(0, 102, 102));
        btnexit3.setText("Update");
        btnexit3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        btnexit3.setContentAreaFilled(false);
        btnexit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexit3ActionPerformed(evt);
            }
        });

        btnexit4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btnexit4.setForeground(new java.awt.Color(0, 102, 102));
        btnexit4.setText("Rekap");
        btnexit4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        btnexit4.setContentAreaFilled(false);
        btnexit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexit4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnexit4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexit3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexit2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexit1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(btnexit3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnexit2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnexit4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(btnexit1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        waktuBerjalan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        waktuBerjalan.setForeground(new java.awt.Color(153, 255, 204));
        waktuBerjalan.setText("jLabel26");

        jamberjalan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jamberjalan.setForeground(new java.awt.Color(153, 255, 204));
        jamberjalan.setText("jLabel26");

        label1.setEditable(false);
        label1.setBackground(new java.awt.Color(0, 102, 102));
        label1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(153, 255, 255));
        label1.setBorder(null);
        label1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label1ActionPerformed(evt);
            }
        });

        label2.setEditable(false);
        label2.setBackground(new java.awt.Color(0, 102, 102));
        label2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(153, 255, 255));
        label2.setBorder(null);
        label2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2ActionPerformed(evt);
            }
        });

        label3.setEditable(false);
        label3.setBackground(new java.awt.Color(0, 102, 102));
        label3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(153, 255, 255));
        label3.setBorder(null);
        label3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label3ActionPerformed(evt);
            }
        });

        label4.setEditable(false);
        label4.setBackground(new java.awt.Color(0, 102, 102));
        label4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(153, 255, 255));
        label4.setBorder(null);
        label4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label4ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/ta/bioskop1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(g1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(g2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addGap(29, 29, 29))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(g3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15)))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(g4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addGap(166, 166, 166)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jamberjalan)
                            .addComponent(waktuBerjalan))))
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(waktuBerjalan)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jamberjalan))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel21))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(172, 172, 172))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String studio, film;
        studio = "Studio 3";
        film = label2.getText();
        film3 kirim = null ;
        try {
            kirim = new film3();
        } catch (SQLException ex) {
            Logger.getLogger(bioskop.class.getName()).log(Level.SEVERE, null, ex);
        }
        kirim.setStudio(studio);
        kirim.cekAll();
        kirim.terima(studio,film);
        kirim.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String studio, film;
        studio = "Studio 4";
        film = label4.getText();
        film4 kirim = null;
        try {
            kirim = new film4();
        } catch (SQLException ex) {
            Logger.getLogger(bioskop.class.getName()).log(Level.SEVERE, null, ex);
        }
        kirim.setStudio(studio);
        kirim.cekAll();
        kirim.terima(studio,film);
        kirim.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String studio, film;
        studio = "Studio 1";
        film = label1.getText();
        film1 kirim = null;
        try {
            kirim = new film1();
        } catch (SQLException ex) {
            Logger.getLogger(bioskop.class.getName()).log(Level.SEVERE, null, ex);
        }
        kirim.setStudio(studio);
        kirim.cekAll();
        kirim.terima(studio,film);
        kirim.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String studio, film;
        studio = "Studio 2";
        film = label3.getText();
        film2 kirim = new film2();
        kirim.setStudio(studio);
        kirim.cekAll();
        kirim.terima(studio,film);
        kirim.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Silhkan datang Kembali!");
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnexit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexit1ActionPerformed
        // TODO add your handling code here:
        
            String sql1, sql2, sql3, sql4;
            sql1 = "TRUNCATE TABLE inputan";
            sql2 = "TRUNCATE TABLE inputan2";
            sql3 = "TRUNCATE TABLE inputan3";
            sql4 = "TRUNCATE TABLE inputan4";
        
         try{
             x.st = x.conn.createStatement();
             x.st.execute(sql1);
             x.st.execute(sql2);
             x.st.execute(sql3);
             x.st.execute(sql4);
         } 
         catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "gagal");
            return;
        }
         JOptionPane.showMessageDialog(null, "Baik Sudah Di reset");
            
    }//GEN-LAST:event_btnexit1ActionPerformed

    private void btnexit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexit2ActionPerformed
        // TODO add your handling code here:
        Menu kirim = new Menu();
        kirim.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnexit2ActionPerformed

    private void label1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label1ActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_label1ActionPerformed

    private void btnexit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexit3ActionPerformed
        // TODO add your handling code here:
        updateFilm kirim = null;
        try {
            kirim = new updateFilm();
        } catch (SQLException ex) {
            Logger.getLogger(bioskop.class.getName()).log(Level.SEVERE, null, ex);
        }
        kirim.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnexit3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(bioskop.MAXIMIZED_BOTH);
        try{  
        String sql;
        sql = "select * from film where id='1'";
        st = conn.createStatement();
        rs = st.executeQuery(sql);
        while(rs.next()){
            label1.setText(rs.getString("namafilm"));
        }
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, "GAGAL");
      }
        
      try{  
        String sql;
        sql = "select * from film where id='2'";
        st = conn.createStatement();
        rs = st.executeQuery(sql);
        while(rs.next()){
            label3.setText(rs.getString("namafilm"));
        }
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, "GAGAL");
      }
      
      try{  
        String sql;
        sql = "select * from film where id='3'";
        st = conn.createStatement();
        rs = st.executeQuery(sql);
        while(rs.next()){
            label2.setText(rs.getString("namafilm"));
        }
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, "GAGAL");
      }
      
      try{  
        String sql;
        sql = "select * from film where id='4'";
        st = conn.createStatement();
        rs = st.executeQuery(sql);
        while(rs.next()){
            label4.setText(rs.getString("namafilm"));
        }
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, "GAGAL");
      }
      try{  
        String sql;
        sql = "select * from film where id='1'";
        st = conn.createStatement();        
        rs = st.executeQuery(sql);      
        while(rs.next()){               
            f1.setText(rs.getString("foto"));
            }
      } 
      catch(Exception e){
          JOptionPane.showMessageDialog(null, "GAGAL");
      }
      try{  
        String sql;
        sql = "select * from film where id='2'";
        st = conn.createStatement();        
        rs = st.executeQuery(sql);      
        while(rs.next()){               
            f2.setText(rs.getString("foto"));
            }
      } 
      catch(Exception e){
          JOptionPane.showMessageDialog(null, "GAGAL");
      }
      try{  
        String sql;
        sql = "select * from film where id='3'";
        st = conn.createStatement();        
        rs = st.executeQuery(sql);      
        while(rs.next()){               
            f3.setText(rs.getString("foto"));
            }
      } 
      catch(Exception e){
          JOptionPane.showMessageDialog(null, "GAGAL");
      }
      try{  
        String sql;
        sql = "select * from film where id='4'";
        st = conn.createStatement();        
        rs = st.executeQuery(sql);      
        while(rs.next()){               
            f4.setText(rs.getString("foto"));
            }
      } 
      catch(Exception e){
          JOptionPane.showMessageDialog(null, "GAGAL");
      }
      
        flm film[] = new flm[4];
        
        film[0] = new flm1();
        film[1] = new flm2();
        film[2] = new flm3();
        film[3] = new flm4();
        
        String file1,file2,file3,file4;
        file1 = f1.getText();
        file2 = f2.getText();
        file3 = f3.getText();
        file4 = f4.getText();
       
        ImageIcon icon = new ImageIcon(file1);
        g1.setIcon(icon);
        
        ImageIcon icon2 = new ImageIcon(file2);
        g2.setIcon(icon2);
        
        ImageIcon icon3 = new ImageIcon(file3);
        g3.setIcon(icon3);
        
        ImageIcon icon4 = new ImageIcon(file4);
        g4.setIcon(icon4);
    }//GEN-LAST:event_formWindowOpened

    private void label2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label2ActionPerformed

    private void label3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label3ActionPerformed

    private void label4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label4ActionPerformed

    private void btnexit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexit4ActionPerformed
        try {
            // TODO add your handling code here:
            rekap kirim = new rekap();
            kirim.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(bioskop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnexit4ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnexit1;
    private javax.swing.JButton btnexit2;
    private javax.swing.JButton btnexit3;
    private javax.swing.JButton btnexit4;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f3;
    private javax.swing.JTextField f4;
    private javax.swing.JLabel g1;
    private javax.swing.JLabel g2;
    private javax.swing.JLabel g3;
    private javax.swing.JLabel g4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jamberjalan;
    private javax.swing.JTextField label1;
    private javax.swing.JTextField label2;
    private javax.swing.JTextField label3;
    private javax.swing.JTextField label4;
    private javax.swing.JLabel waktuBerjalan;
    // End of variables declaration//GEN-END:variables
}
