/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta;

import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Asus
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public int hargaGulai = 10;
    public int hargaSotoIblis = 10;
    public int hargaRawon = 12;
    public int hargaCotoMakassar = 15;
    public int jmlGulai;
    public int jmlSotoIblis;
    public int jmlRawon;
    public int jmlCotoMakassar;
    
    
    public Menu() {
        initComponents();
    }
    
    public void TampilTotal(){
        int jml = 0;
        jml += this.hargaGulai*this.jmlGulai;
        jml += this.hargaSotoIblis*this.jmlSotoIblis;
        jml += this.hargaRawon*this.jmlRawon;
        jml += this.hargaCotoMakassar*this.jmlCotoMakassar;
        
        lbtotal.setText("IDR. "+jml+"K");
  
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        print = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbtotal1 = new javax.swing.JTextArea();
        cetak = new javax.swing.JButton();
        lbtotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfcotomakassar = new javax.swing.JTextField();
        lbcotomakassar = new javax.swing.JLabel();
        lbrawon = new javax.swing.JLabel();
        tfrawon = new javax.swing.JTextField();
        cbcotomakassar = new javax.swing.JCheckBox();
        cbrawon = new javax.swing.JCheckBox();
        lbsotoiblis = new javax.swing.JLabel();
        lbgulai = new javax.swing.JLabel();
        tfgulai = new javax.swing.JTextField();
        tfsotoiblis = new javax.swing.JTextField();
        cbsotoiblis = new javax.swing.JCheckBox();
        cbgulai = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtpopcorn = new javax.swing.JTextField();
        txtkentang = new javax.swing.JTextField();
        txtteh = new javax.swing.JTextField();
        txtsoda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        jLabel4.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        print.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        print.setText("print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        lbtotal1.setEditable(false);
        lbtotal1.setColumns(20);
        lbtotal1.setRows(5);
        jScrollPane2.setViewportView(lbtotal1);

        cetak.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cetak.setText("cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        lbtotal.setEditable(false);
        lbtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbtotalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 102));
        jLabel2.setText("total :");

        tfcotomakassar.setEditable(false);
        tfcotomakassar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfcotomakassar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfcotomakassarKeyReleased(evt);
            }
        });

        lbcotomakassar.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbcotomakassar.setForeground(new java.awt.Color(0, 204, 204));
        lbcotomakassar.setText("IDR.0K");

        lbrawon.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbrawon.setForeground(new java.awt.Color(0, 204, 204));
        lbrawon.setText("IDR.0K");

        tfrawon.setEditable(false);
        tfrawon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfrawon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfrawonKeyReleased(evt);
            }
        });

        cbcotomakassar.setBackground(new java.awt.Color(0, 102, 102));
        cbcotomakassar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbcotomakassar.setForeground(new java.awt.Color(0, 204, 204));
        cbcotomakassar.setText("Es Soda");
        cbcotomakassar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcotomakassarActionPerformed(evt);
            }
        });

        cbrawon.setBackground(new java.awt.Color(0, 102, 102));
        cbrawon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbrawon.setForeground(new java.awt.Color(0, 204, 204));
        cbrawon.setText("Teh Tarik");
        cbrawon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrawonActionPerformed(evt);
            }
        });

        lbsotoiblis.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbsotoiblis.setForeground(new java.awt.Color(0, 204, 204));
        lbsotoiblis.setText("IDR.0K");

        lbgulai.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbgulai.setForeground(new java.awt.Color(0, 204, 204));
        lbgulai.setText("IDR.0K");

        tfgulai.setEditable(false);
        tfgulai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfgulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfgulaiActionPerformed(evt);
            }
        });
        tfgulai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfgulaiKeyReleased(evt);
            }
        });

        tfsotoiblis.setEditable(false);
        tfsotoiblis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfsotoiblis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsotoiblisActionPerformed(evt);
            }
        });
        tfsotoiblis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfsotoiblisKeyReleased(evt);
            }
        });

        cbsotoiblis.setBackground(new java.awt.Color(0, 102, 102));
        cbsotoiblis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbsotoiblis.setForeground(new java.awt.Color(0, 204, 204));
        cbsotoiblis.setText("Kentang Goreng");
        cbsotoiblis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsotoiblisActionPerformed(evt);
            }
        });

        cbgulai.setBackground(new java.awt.Color(0, 102, 102));
        cbgulai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbgulai.setForeground(new java.awt.Color(0, 204, 204));
        cbgulai.setText("Popcorn Special");
        cbgulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgulaiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 102));
        jLabel1.setText("Menu Snack");

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 204, 204));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(txtpopcorn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(txtkentang, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(txtteh, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtsoda, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfgulai, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfsotoiblis, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbcotomakassar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfcotomakassar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(lbcotomakassar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lbtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(cbrawon, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfrawon, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(78, 78, 78)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbgulai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbsotoiblis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(254, 254, 254)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbgulai, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbrawon, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbsotoiblis, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(820, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(tfgulai, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfsotoiblis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbrawon, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(tfrawon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbcotomakassar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbcotomakassar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfcotomakassar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpopcorn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkentang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(38, 38, 38)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbgulai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbgulai, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbsotoiblis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbsotoiblis, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addComponent(lbrawon, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addGap(401, 401, 401)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbgulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgulaiActionPerformed
        if(cbgulai.isSelected()==true){
            tfgulai.setEditable(true);
            tfgulai.setText("1");
            lbgulai.setText("IDR. 10K");
            
            this.jmlGulai = 1;
        }
        else{
            tfgulai.setEditable(false);
            tfgulai.setText("");
            lbgulai.setText("IDR. 0K");
            
            this.jmlGulai = 0;
        }
        this.TampilTotal();
    }//GEN-LAST:event_cbgulaiActionPerformed

    private void tfsotoiblisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsotoiblisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsotoiblisActionPerformed

    private void cbsotoiblisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsotoiblisActionPerformed
        if(cbsotoiblis.isSelected()==true){
            tfsotoiblis.setEditable(true);
            tfsotoiblis.setText("1");
            lbsotoiblis.setText("IDR. 10K");
            
            this.jmlSotoIblis = 1;
        }
        else{
            tfsotoiblis.setEditable(false);
            tfsotoiblis.setText("");
            lbsotoiblis.setText("IDR. 0K");
            
            this.jmlSotoIblis = 0;
        }
        this.TampilTotal();
    }//GEN-LAST:event_cbsotoiblisActionPerformed

    private void cbrawonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrawonActionPerformed
        if(cbrawon.isSelected()==true){
            tfrawon.setEditable(true);
            tfrawon.setText("1");
            lbrawon.setText("IDR. 12K");
            
            this.jmlRawon = 1;
        }
        else{
            tfrawon.setEditable(false);
            tfrawon.setText("");
            lbrawon.setText("IDR. 0K");
            
            this.jmlRawon = 0;
        }
        this.TampilTotal();
    }//GEN-LAST:event_cbrawonActionPerformed

    private void cbcotomakassarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcotomakassarActionPerformed
        if(cbcotomakassar.isSelected()==true){
            tfcotomakassar.setEditable(true);
            tfcotomakassar.setText("1");
            lbcotomakassar.setText("IDR. 15K");
            
            this.jmlCotoMakassar = 1;
        }
        else{
            tfcotomakassar.setEditable(false);
            tfcotomakassar.setText("");
            lbcotomakassar.setText("IDR. 0K");
            
            this.jmlCotoMakassar = 0;
        }
        this.TampilTotal();
    }//GEN-LAST:event_cbcotomakassarActionPerformed

    private void tfgulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfgulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfgulaiActionPerformed

    private void tfgulaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfgulaiKeyReleased
        int jml = Integer.parseInt(tfgulai.getText());
        int subtotal =jml*this.hargaGulai;
        
        this.jmlGulai = jml;
        
        lbgulai.setText("IDR. "+subtotal+"K");
        
        this.TampilTotal();
    }//GEN-LAST:event_tfgulaiKeyReleased

    private void tfsotoiblisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfsotoiblisKeyReleased
         int jml = Integer.parseInt(tfsotoiblis.getText());
        int subtotal =jml*this.hargaSotoIblis;
        
        this.jmlSotoIblis = jml;
        
        lbsotoiblis.setText("IDR. "+subtotal+"K");
        
        this.TampilTotal();
    }//GEN-LAST:event_tfsotoiblisKeyReleased

    private void tfrawonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfrawonKeyReleased
         int jml = Integer.parseInt(tfrawon.getText());
        int subtotal =jml*this.hargaRawon;
        
        this.jmlRawon = jml;
        
        lbrawon.setText("IDR. "+subtotal+"K");
        
        this.TampilTotal();
    }//GEN-LAST:event_tfrawonKeyReleased

    private void tfcotomakassarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcotomakassarKeyReleased
         int jml = Integer.parseInt(tfcotomakassar.getText());
        int subtotal =jml*this.hargaCotoMakassar;
        
        this.jmlCotoMakassar = jml;
        
        lbcotomakassar.setText("IDR. "+subtotal+"K");
        
        this.TampilTotal();
    }//GEN-LAST:event_tfcotomakassarKeyReleased

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try {
            lbtotal1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printActionPerformed

    private void lbtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbtotalActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
        
        if(cbgulai.isSelected() == true){
            txtpopcorn.setText(cbgulai.getText());
        }
        if(cbsotoiblis.isSelected() == true){
            txtkentang.setText(cbsotoiblis.getText());
        }
        if(cbrawon.isSelected() == true){
            txtteh.setText(cbrawon.getText());
        }
        if(cbcotomakassar.isSelected() == true){
            txtsoda.setText(cbcotomakassar.getText());
        }
        
        lbtotal1.append(" \n Struk makanan \n\n" +
                "\n======================================\n"+
                "Snack\t :\tJumlah\n"+txtpopcorn.getText()+"\t"+tfgulai.getText()+"\n"+
                ""+txtkentang.getText()+"\t"+tfsotoiblis.getText()+"\n"+
                ""+txtteh.getText()+"\t\t"+tfrawon.getText()+"\n"+
                ""+txtsoda.getText()+"\t\t"+tfcotomakassar.getText()+"\n\n"+
                "Bayar\t="+lbtotal.getText()+"\n\n"+
                "======================================"
        
        );
        
        
        
        
    }//GEN-LAST:event_cetakActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        bioskop bioskop = null;
        try {
            bioskop = new bioskop();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        bioskop.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        lbtotal1.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox cbcotomakassar;
    private javax.swing.JCheckBox cbgulai;
    private javax.swing.JCheckBox cbrawon;
    private javax.swing.JCheckBox cbsotoiblis;
    private javax.swing.JButton cetak;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbcotomakassar;
    private javax.swing.JLabel lbgulai;
    private javax.swing.JLabel lbrawon;
    private javax.swing.JLabel lbsotoiblis;
    private javax.swing.JTextField lbtotal;
    private javax.swing.JTextArea lbtotal1;
    private javax.swing.JButton print;
    private javax.swing.JTextField tfcotomakassar;
    private javax.swing.JTextField tfgulai;
    private javax.swing.JTextField tfrawon;
    private javax.swing.JTextField tfsotoiblis;
    private javax.swing.JTextField txtkentang;
    private javax.swing.JTextField txtpopcorn;
    private javax.swing.JTextField txtsoda;
    private javax.swing.JTextField txtteh;
    // End of variables declaration//GEN-END:variables
}
